platform :ios, '9.0'

target 'toDoProject' do
  use_frameworks!
  pod 'RealmSwift'


  # Pods for toDoProject

  target 'toDoProjectTests' do
    inherit! :search_paths
  end

  target 'toDoProjectUITests' do
    inherit! :search_paths
  end

end
